name: Leapp Desktop App Test CI

on:
  push:
    branches:
      - LEAP-680-spike-integration-tests

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Project
        run: |
          npm run bootstrap
          npm run set-dev-environment
          cd packages/desktop-app

      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run integration-test
